import type {
  ParticipantAttachment,
  ParticipantConversationPage,
  ParticipantConversationSummary,
  ParticipantMessage,
  ParticipantSubjectRef,
} from '@adatechnology/conversation-contracts'

export type ParticipantSendInput = {
  readonly subject: ParticipantSubjectRef
  /** Generated by the package (crypto.randomUUID). The host uses it as Idempotency-Key; a resend repeats it. */
  readonly clientMessageId: string
  readonly text?: string
  readonly files?: readonly File[]
}

export type ParticipantSendResult =
  | { readonly outcome: 'sent'; readonly message: ParticipantMessage }
  | { readonly outcome: 'queued' }

export type ParticipantConversationEvent =
  | { readonly type: 'inbox-changed' }
  | { readonly type: 'conversation-changed'; readonly subject: ParticipantSubjectRef }

export interface ParticipantConversationsApi {
  listConversations(params?: { readonly cursor?: string }): Promise<ParticipantConversationPage>
  fetchMessages(
    subject: ParticipantSubjectRef,
    params?: { readonly before?: string; readonly limit?: number },
  ): Promise<readonly ParticipantMessage[]>
  /** Throwing means failed; the package shows a retry affordance and repeats the SAME clientMessageId. */
  sendMessage(input: ParticipantSendInput): Promise<ParticipantSendResult>
  /** Marks the other side's messages of THAT subject as read, never "all". */
  markRead(subject: ParticipantSubjectRef): Promise<void>
  resolveAttachmentUrl(attachment: ParticipantAttachment, disposition?: 'inline' | 'attachment'): Promise<string>
  openConversation?(subject: ParticipantSubjectRef): Promise<ParticipantConversationSummary>
  subscribe?(listener: (event: ParticipantConversationEvent) => void): () => void
}

type ParticipantPendingAttachment = {
  readonly filename: string
  readonly mimeType: string
  readonly sizeBytes: number
}

/** Message the host keeps in its durable queue and hands back to the package. */
export type ParticipantPendingMessage = {
  readonly clientMessageId: string
  readonly subject: ParticipantSubjectRef
  readonly text?: string
  readonly attachments?: readonly ParticipantPendingAttachment[]
  readonly createdAt: string
  readonly state: 'queued' | 'failed'
}

/** Message still living only in the memory of the screen: being sent, queued by the host and not yet reflected, or failed. */
export type ParticipantLocalPendingMessage = Omit<ParticipantPendingMessage, 'state'> & {
  readonly state: 'sending' | 'queued' | 'failed'
}
