export { MessageBubble } from './MessageBubble'
export { ConversationWallpaper } from './Wallpaper'
export { ConversationLocalesProvider, useConversationLocales } from './ConversationLocalesProvider'
export { AudioPlayer } from './AudioPlayer'
export { EmojiPicker } from './EmojiPicker'
export { MessageComposer } from './MessageComposer'
export { WhatsAppMessageEditor } from './WhatsAppMessageEditor'
export { SimpleEmojiPicker } from './SimpleEmojiPicker'
export { DateDivider } from './DateDivider'
export { Avatar } from './Avatar'
export { ConversationListItem } from './ConversationListItem'
export { ToastProvider, useToast, toast } from './Toast'

export { StatusTicks } from './StatusTicks'
export { Lightbox } from './Lightbox'
export { MediaRenderer } from './MediaRenderer'
export { FileIcon } from './FileIcon'
export { MessageText } from './MessageText'
export { MessageTimestamp } from './MessageTimestamp'
export { MessageTail } from './MessageTail'

export { useDarkMode } from './useDarkMode'
export { useWaitingNotifications } from './useWaitingNotifications'

export { ConversationsProvider, useConversations } from './providers/ConversationsProvider'

// Camada headless (T6.9) — hooks de dados/ações independentes de qualquer tela, para o
// produto montar sua própria UI sobre eles. Requerem <ConversationsProvider> como ancestral.
export { useConversationMessages } from './hooks/useConversationMessages'
export { useConversationList } from './hooks/useConversationList'
export { useConversationContext } from './hooks/useConversationContext'
export { useConversationDocuments } from './hooks/useConversationDocuments'
export { useConversationRealtime, useGlobalRealtime } from './hooks/useConversationRealtime'

export { parseWhatsAppFormatting, waToHTML, htmlToWA, waToHTMLInline } from './lib/whatsapp-formatting'
export { formatPhone, phoneInitials } from './lib/phone'
export { formatTimestamp, formatFileSize } from './lib/format'

export type { MessagePayload, ConversationsUIConfig, ConversationsTheme, ConversationsFeatures } from './types'
export type { ConversationsApi, SSEProvider, ConversationSummary, ConversationDocument } from './providers/types'

export type { MessageBubbleProps } from './MessageBubble'
export type { ConversationWallpaperProps } from './Wallpaper'
export type { ConversationLocales, ConversationLocalesProviderProps } from './ConversationLocalesProvider'
export type { AudioPlayerProps } from './AudioPlayer'
export type { EmojiPickerProps } from './EmojiPicker'
export type { MessageComposerProps } from './MessageComposer'
export type { WhatsAppMessageEditorProps } from './WhatsAppMessageEditor'
export type { SimpleEmojiPickerProps } from './SimpleEmojiPicker'
export type { DateDividerProps } from './DateDivider'
export type { AvatarProps } from './Avatar'
export type { ConversationListItemProps } from './ConversationListItem'
export type { StatusTicksProps } from './StatusTicks'
export type { LightboxProps } from './Lightbox'
export type { MediaRendererProps, ResolveMediaUrl } from './MediaRenderer'
export type { FileIconProps } from './FileIcon'
export type { MessageTextProps } from './MessageText'

export type { UseConversationMessagesResult } from './hooks/useConversationMessages'
export type { UseConversationListParams, UseConversationListResult } from './hooks/useConversationList'
export type { UseConversationContextResult } from './hooks/useConversationContext'
export type { UseConversationDocumentsParams, UseConversationDocumentsResult } from './hooks/useConversationDocuments'
export type { ConversationRealtimeHandler } from './hooks/useConversationRealtime'
export type { AsyncResourceState } from './hooks/useAsyncResource'
