/**
 * Copyright (c) 2026 Ada Technology. MIT License.
 */
export const SECRET_ENVELOPE_VERSION = 1
export const SECRET_ENVELOPE_ALGORITHM = 'A256GCM'
export const SECRET_KEY_SIZE_BYTES = 32
export const SECRET_NONCE_SIZE_BYTES = 12
export const SECRET_AUTHENTICATION_TAG_SIZE_BITS = 128
export const SECRET_AUTHENTICATION_TAG_SIZE_BYTES = 16
export const SECRET_PLAINTEXT_LIMIT_BYTES = 1_048_576
export const SECRET_CIPHERTEXT_LIMIT_BYTES = SECRET_PLAINTEXT_LIMIT_BYTES + SECRET_AUTHENTICATION_TAG_SIZE_BYTES
