/**
 * Copyright (c) 2026 Ada Technology. MIT License.
 */

export {
  RESOURCE_KIND,
  AVAILABILITY_EXCEPTION_KIND,
  BOOKING_STATUS,
  BOOKING_PARTICIPANT_ROLE,
  BOOKING_PARTICIPANT_RESPONSE_STATUS,
} from './scheduling.types'
export type {
  ResourceId,
  ServiceId,
  AvailabilityRuleId,
  AvailabilityExceptionId,
  BookingId,
  BookingSlotId,
  BookingParticipantId,
  CompanyId,
  TimeRange,
  ResourceKind,
  AvailabilityExceptionKind,
  BookingStatus,
  BookingParticipantRole,
  BookingParticipantResponseStatus,
  Resource,
  Service,
  ResourceService,
  AvailabilityRule,
  AvailabilityException,
  Booking,
  BookingSlot,
  BookingParticipant,
  AvailableSlot,
  PaginatedResponse,
  CreateResourceInput,
  UpdateResourceInput,
  CreateServiceInput,
  UpdateServiceInput,
  CreateAvailabilityRuleInput,
  CreateAvailabilityExceptionInput,
  RequestBookingInput,
  RescheduleBookingInput,
  CancelBookingInput,
  ListResourcesParams,
  ListServicesParams,
  ListBookingsParams,
  GetAvailabilityParams,
} from './scheduling.types'

export {
  ianaTimezoneSchema,
  createResourceSchema,
  updateResourceSchema,
  createServiceSchema,
  updateServiceSchema,
  createAvailabilityRuleSchema,
  createAvailabilityExceptionSchema,
  requestBookingSchema,
  rescheduleBookingSchema,
  cancelBookingSchema,
  listResourcesQuerySchema,
  listServicesQuerySchema,
  listBookingsQuerySchema,
  getAvailabilityQuerySchema,
} from './schemas'
export type {
  CreateResourceBody,
  UpdateResourceBody,
  CreateServiceBody,
  UpdateServiceBody,
  CreateAvailabilityRuleBody,
  CreateAvailabilityExceptionBody,
  RequestBookingBody,
  RescheduleBookingBody,
  CancelBookingBody,
  ListResourcesQuery,
  ListServicesQuery,
  ListBookingsQuery,
  GetAvailabilityQuery,
} from './schemas'

export type {
  AuthContext,
  AuthContextResolverPort,
  VideoMeetingRequest,
  VideoMeetingOutcome,
  VideoMeetingPort,
  CalendarEventPayload,
  CalendarSyncOutcome,
  CalendarSyncPort,
  ClockPort,
  LoggerPort,
  LogMeta,
  SchedulingModuleConfig,
} from './providers'

export { SCHEDULING_EVENT } from './events'
export type {
  SchedulingEvent,
  BookingRequestedEvent,
  BookingConfirmedEvent,
  BookingRescheduledEvent,
  BookingCancelledEvent,
  BookingReminderDueEvent,
  BookingCompletedEvent,
  BookingNoShowEvent,
  SchedulingHooks,
} from './events'

export {
  SchedulingError,
  SCHEDULING_ERROR_CODES,
  ResourceNotFoundError,
  ServiceNotFoundError,
  BookingNotFoundError,
  SlotUnavailableError,
  CancellationTooLateError,
  BookingInPastError,
  ResourceUnavailableError,
  ServiceNotOfferedByResourceError,
  ConfigMissingError,
} from './errors'
